// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace DDX.OrderManagementSystem.App
{
    public class EvaluationListResult
    {
        public string orderId { get; set; }
    }
    public class EvaluationRoot
    {
        public EvaluationListResult[] listResult { get; set; }
        public bool success { get; set; }
        public int totalItem { get; set; }
    }

    public class AliMessage
    {
        public bool haveFile { get; set; }
        public string orderUrl { get; set; }
        public string gmtCreate { get; set; }
        public string receiverLoginId { get; set; }
        public string messageType { get; set; }
        public string fileUrl { get; set; }
        public int productId { get; set; }
        public int id { get; set; }
        public string content { get; set; }
        public string senderName { get; set; }
        public string senderLoginId { get; set; }
        public string productUrl { get; set; }
        public bool read { get; set; }
        public string receiverName { get; set; }
        public object typeId { get; set; }
        public string productName { get; set; }
        public object orderId { get; set; }
        public string relationId { get; set; }
    }

    public class AliMessageList
    {
        public int total { get; set; }
        public List<AliMessage> msgList { get; set; }
        public bool success { get; set; }
    }
    public class Currency
    {
        public string defaultFractionDigits;
        public string currencyCode;
        public string symbol;
    }

    public class LogisticsAmount
    {
        public double amount;
        public int cent;
        public string currencyCode;
        public int centFactor;
        public Currency currency;
    }


    public class TotalProductAmount
    {
        public double amount;
        public int cent;
        public string currencyCode;
        public int centFactor;
        public Currency currency;
    }


    public class ProductUnitPrice
    {
        public double amount;
        public int cent;
        public string currencyCode;
        public int centFactor;
        public Currency currency;
    }

    public class ProductList
    {
        public string childId;
        public int goodsPrepareTime;
        public LogisticsAmount logisticsAmount;
        public string memo;
        public string sellerSignerFirstName;
        public TotalProductAmount totalProductAmount;
        public string freightCommitDay;
        public bool canSubmitIssue;
        public string productUnit;
        public string logisticsType;
        public string issueStatus;
        public string orderId;
        public string logisticsServiceName;
        public string sonOrderStatus;
        public string productSnapUrl;
        public bool moneyBack3x;
        public string sendGoodsTime;
        public string skuCode;
        public string productId;
        public int productCount;
        public string deliveryTime;
        public ProductUnitPrice productUnitPrice;
        public string sellerSignerLastName;
        public string productImgUrl;
        public string showStatus;
        public string productName;
    }



    public class PayAmount
    {
        public double amount;
        public int cent;
        public string currencyCode;
        public int centFactor;
        public Currency currency;
    }

    public class OrderList
    {
        public ProductList[] productList;
        public string issueStatus;
        public string frozenStatus;
        public string buyerLoginId;
        public string sellerSignerFullname;
        public bool hasRequestLoan;
        public string orderId;
        public PayAmount payAmount;
        public string gmtCreate;
        public string paymentType;
        public string orderStatus;
        public string buyerSignerFullname;
        public string gmtPayTime;
        public object timeoutLeftTime;
        public string fundStatus;
        public string gmtSendGoodsTime;

        public string bizType;
    }




    public class AliOrderListType
    {
        public int totalItem;
        public OrderList[] orderList;
    }
    public class ReceiptAddress
    {
        public string zip;
        public string address2;
        public string detailAddress;
        public string country;
        public string city;
        public string phoneNumber;
        public string province;
        public string phoneArea;
        public string phoneCountry;
        public string contactPerson;
        public string mobileNo;
    }

    public class BuyerInfo
    {
        public string lastName;
        public string loginId;
        public string email;
        public string firstName;
        public string country;
    }



    public class UnitPrice
    {
        public double amount;
        public int cent;
        public string currencyCode;
        public int centFactor;
        public Currency currency;
    }

    public class ChildOrderExtInfoList
    {
        public UnitPrice unitPrice;
        public int quantity;
        public string sku;
        public string productName;
        public string productId;
    }

    public class IssueInfo
    {
        public string issueStatus;
    }

    public class LogisticInfoList
    {
        public string logisticsTypeCode;
        public string logisticsNo;
        public string logisticsServiceName;
        public string gmtSend;
        public string receiveStatus;
    }

    public class OrderAmount
    {
        public double amount;
        public int cent;
        public string currencyCode;
        public int centFactor;
        public Currency currency;
    }


    public class InitOderAmount
    {
        public double amount;
        public int cent;
        public string currencyCode;
        public int centFactor;
        public Currency currency;
    }

    public class InitOrderAmt
    {
        public double amount;
        public int cent;
        public string currencyCode;
        public int centFactor;
        public Currency currency;
    }

    public class ProductPrice
    {
        public double amount;
        public int cent;
        public string currencyCode;
        public int centFactor;
        public Currency currency;
    }

    public class ChildOrderList
    {
        public int lotNum;
        public string productAttributes;
        public string orderStatus;
        public string productUnit;
        public string skuCode;
        public string productId;
        public string id;
        public string issueStatus;
        public string frozenStatus;
        public int productCount;
        public string fundStatus;
        public InitOrderAmt initOrderAmt;
        public ProductPrice productPrice;
        public string productName;
    }

    public class LoanInfo
    {
    }

    public class AliOrderType
    {
        public ReceiptAddress receiptAddress;
        public string gmtModified;
        public BuyerInfo buyerInfo;
        public string buyerloginid;
        public LogisticsAmount logisticsAmount;
        public ChildOrderExtInfoList[] childOrderExtInfoList;
        public object[] orderMsgList;
        public IssueInfo issueInfo;
        public LogisticInfoList[] logisticInfoList;
        public string id;
        public string issueStatus;
        public string frozenStatus;
        public string logisticsStatus;
        public OrderAmount orderAmount;
        public string sellerSignerFullname;
        public InitOderAmount initOderAmount;
        public ChildOrderList[] childOrderList;
        public string gmtCreate;
        public string sellerOperatorLoginId;
        public LoanInfo loanInfo;
        public string orderStatus;
        public string buyerSignerFullname;
        public string loanStatus;
        public string gmtPaySuccess;
        public string fundStatus;
    }


    public class SkuType
    {
        public int order;
        public int pId;
        public string pName;
        public string pValue;
        public int pValueId;
        public string selfDefineValue;
        public string showType;
        public string skuImg;
    }

    public class SkuListType
    {
        public SkuType[] sku;
    }

    public class OrderMsgType
    {
        public string id { get; set; }
        public string gmtCreate { get; set; }
        public string senderName { get; set; }
        public string messageType { get; set; }
        public string content { get; set; }
        public string typeId { get; set; }
        public string filePath { get; set; }
        public string summary { get; set; }

    }
    public class OrderMsgTypeList
    {

        public OrderMsgType[] result { set; get; }
    }


    public class LogisticsResult
    {
        public string logisticsServiceName { get; set; }
        public string trialResult { get; set; }
        public string logisticsTimeliness { get; set; }
        public string logisticsServiceId { get; set; }
        public string deliveryAddress { get; set; }
    }

    public class LogisticsRootObject
    {
        public List<LogisticsResult> result { get; set; }
        public string success { get; set; }
        
    }
    public class OnlineLogisticsServiceListByOrderIdReturn
    {
        public List<AeopOnlineLogisticsServiceResult> result { get; set; }
        public bool success { get; set; }
        public string errorDesc { get; set; }
    }
    public class AeopOnlineLogisticsServiceResult
    {
        public string logisticsServiceId { get; set; }
        public string logisticsServiceName { get; set; }
        public string logisticsTimeliness { get; set; }
        public string deliveryAddress { get; set; }
        public string trialResult { get; set; }
        public string warehouseName { get; set; }
        public List<AeopOnlineLogisticsFeeItem> otherFees { get; set; }
        public bool isExpressLogisticsService { get; set; }

    }
    public class AeopOnlineLogisticsFeeItem
    {
        public string code { get; set; }
        public string name { get; set; }
        public string currency { get; set; }
        public double amount { get; set; }
    }
    public class AliReceiver
    {
        public string city { get; set; }
        public string country { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string postcode { get; set; }
        public string province { get; set; }
        public string streetAddress { get; set; }
    }

    public class AliSender
    {
        public string city { get; set; }
        public string country { get; set; }
        public string county { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string postcode { get; set; }
        public string province { get; set; }
        public string streetAddress { get; set; }
        public int addressId { get; set; }
    }

    public class AliPickup
    {
        public string city { get; set; }
        public string county { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string name { get; set; }
        public string postcode { get; set; }
        public string province { get; set; }
        public string streetAddress { get; set; }
        public int addressId { get; set; }
    }

    public class AliRefund
    {
        public string city { get; set; }
        public string county { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string name { get; set; }
        public string postcode { get; set; }
        public string province { get; set; }
        public string streetAddress { get; set; }
        public int addressId { get; set; }
    }

    public class AliOrderAddressRootObject
    {
        public AliReceiver receiver { get; set; }
        public AliSender sender { get; set; }
        public AliPickup pickup { get; set; }
        public AliRefund refund { get; set; }
    }
   
    public class SellerAddressesList
    {
        public List<AddressDTOs> pickupSellerAddressesList { get; set; }
        public List<AddressDTOs> senderSellerAddressesList { get; set; }
        public List<AddressDTOs> refundSellerAddressesList { get; set; }
    }
    public class AddressDTOs
    {
        public string city { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string memberType { get; set; }
        public string mobile { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string postcode { get; set; }
        public string province { get; set; }
        public string streetAddress { get; set; }
        public string trademanageId { get; set; }
        public string county { get; set; }
        public string street { get; set; }
        public int addressId { get; set; }
        public bool isDefault { get; set; }
    }
   

    public class LogisticsGoods
    {
        public string categoryCnDesc { get; set; }
        public string categoryEnDesc { get; set; }
        public string isContainsBattery { get; set; }
        public string productDeclareAmount { get; set; }
        public string productId { get; set; }
        public string productNum { get; set; }
        public string productWeight { get; set; }
    }
    public class SendResult
    {
        public string warehouseOrderId { get; set; }
        public string tradeOrderId { get; set; }
        public string errorCode { get; set; }
        public string tradeOrderFrom { get; set; }
        public string success { get; set; }
        public string outOrderId { get; set; }
    }

    public class AliOrderSendRootObject
    {
        public SendResult result { get; set; }
        public string success { get; set; }
    }

    public class AliTrackCodeResult
    {
        public string logisticsStatus { get; set; }
        public string internationalLogisticsType { get; set; }
        public string internationallogisticsId { get; set; }
        public string orderId { get; set; }
        public string onlineLogisticsId { get; set; }
    }

    public class AliTrackCodeRootObject
    {
        public List<AliTrackCodeResult> result { get; set; }
        public string currentPage { get; set; }
        public string success { get; set; }
        public string totalPage { get; set; }
    }


    public class AliPDFRootObject
    {
        public string StatusCode { get; set; }
        public string body { get; set; }
        public string ContentDisposition { get; set; }
        public string ContentType { get; set; }
    }
    #region 无忧普货和化妆品
    public class AddressOrderDTOs
    {
        public AliReceiver receiver { get; set; }
        public AliSender sender { get; set; }
        public AliPickup pickup { get; set; }
        public AliRefund refund { get; set; }
    }
    public class AddressDTO
    {
        public string city { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string memberType { get; set; }
        public string mobile { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string postcode { get; set; }
        public string province { get; set; }
        public string streetAddress { get; set; }
        public string trademanageId { get; set; }
        public string county { get; set; }
        public string street { get; set; }
        public int addressId { get; set; }
    }
    public class AliCreateWarehouseOrderResultDTO
    {
        public bool success { get; set; }
        public string warehouseOrderId { get; set; }
        public string intlTrackingNo { get; set; }
        public string tradeOrderFrom { get; set; }
        public string tradeOrderId { get; set; }
        public string outOrderId { get; set; }
        public int errorCode { get; set; }
        public string errorDesc { get; set; }
    }
    public class AlicreateWarehouseOrderReturn
    {
        public AliCreateWarehouseOrderResultDTO result { get; set; }
        public bool Success { get; set; }
    }
    public class AeopWlDeclareProductDTO
    {
        public string productId { get; set; }
        public string categoryCnDesc { get; set; }
        public string categoryEnDesc { get; set; }
        public int productNum { get; set; }
        public double productDeclareAmount { get; set; }
        public double productWeight { get; set; }
        public int isContainsBattery { get; set; }
        public string scItemId { get; set; }
        public string skuValue { get; set; }
        public string skuCode { get; set; }
        public string scItemName { get; set; }
        public string scItemCode { get; set; }
        public string hsCode { get; set; }
        public byte isAneroidMarkup { get; set; }
        public byte isOnlyBattery { get; set; }
        public byte isBreakable { get; set; }
    }
    public class AlicreateWarehouseOrderRequest
    {
        public string tradeOrderId { get; set; }
        public string tradeOrderFrom { get; set; }
        public string warehouseCarrierService { get; set; }
        public string domesticLogisticsCompanyId { get; set; }
        public string domesticLogisticsCompany { get; set; }
        public string domesticTrackingNo { get; set; }
        public string remark { get; set; }
        public List<AeopWlDeclareProductDTO> declareProductDTOs { get; set; }
        public AddressDTOs addressDTOs { get; set; }
        public int undeliverableDecision { get; set; }
        public int packageNum { get; set; }
    }
    public class AeopLogisticsServiceResult
    {
        public string logisticsCompany { get; set; }
        public string displayName { get; set; }
        public string serviceName { get; set; }
        public int minProcessDay { get; set; }
        public int maxProcessDay { get; set; }
        public string trackingNoRegex { get; set; }
        public int recommendOrder { get; set; }
    }
#endregion
}
