//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDX.OrderManagementSystem.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservice.webxml.com.cn/WebServices/ForexRmbRateWebService.asmx")]
        public string DDX_OrderManagementSystem_App_cn_com_webxml_webservice_ForexRmbRateWebService {
            get {
                return ((string)(this["DDX_OrderManagementSystem_App_cn_com_webxml_webservice_ForexRmbRateWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.apacshipping.ebay.com.hk/aspapi/v4/ApacShippingService")]
        public string DDX_OrderManagementSystem_App_asp_ebay_shipping_ApacShippingService {
            get {
                return ((string)(this["DDX_OrderManagementSystem_App_asp_ebay_shipping_ApacShippingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://yewu.chukou1.cn/client/ws/v2.1/ck1.asmx")]
        public string DDX_OrderManagementSystem_App_cn_chukou1_demo_CK1 {
            get {
                return ((string)(this["DDX_OrderManagementSystem_App_cn_chukou1_demo_CK1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.tea-post.com/OrderOnline/ws/OrderOnlineService.dll")]
        public string DDX_OrderManagementSystem_App_TeaPostApi_OrderOnlineServiceImplService {
            get {
                return ((string)(this["DDX_OrderManagementSystem_App_TeaPostApi_OrderOnlineServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wsvc.cdiscount.com/MarketplaceAPIService.svc")]
        public string DDX_OrderManagementSystem_App_com_cdiscount_wsvc_MarketplaceAPIService {
            get {
                return ((string)(this["DDX_OrderManagementSystem_App_com_cdiscount_wsvc_MarketplaceAPIService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://post.8dt.com:8880/wb_lc/cxf/ParcelOprWebService")]
        public string DDX_OrderManagementSystem_App_com_bdt_post_ParcelOprWebService {
            get {
                return ((string)(this["DDX_OrderManagementSystem_App_com_bdt_post_ParcelOprWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://121.40.249.183/default/svc/web-service")]
        public string DDX_OrderManagementSystem_App_com_qucanq_wsvc_Ec {
            get {
                return ((string)(this["DDX_OrderManagementSystem_App_com_qucanq_wsvc_Ec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://120.24.229.25:908/default/svc/web-service")]
        public string DDX_OrderManagementSystem_App_com_suyou_wsvc_Ec {
            get {
                return ((string)(this["DDX_OrderManagementSystem_App_com_suyou_wsvc_Ec"]));
            }
        }
    }
}
