//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DDX.OrderManagementSystem.App.asp.ebay.shipping {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ApacShippingServiceSoap", Namespace="http://api.apacshipping.ebay.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseRequest))]
    public partial class ApacShippingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddAPACShippingPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelAPACShippingPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmAPACShippingPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAPACShippingLabelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAPACShippingLabelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAPACShippingPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAPACShippingPackageStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAPACShippingRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyAPACShippingUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecreateAPACShippingPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAPACShippingTrackCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ApacShippingService() {
            this.Url = global::DDX.OrderManagementSystem.App.Properties.Settings.Default.DDX_OrderManagementSystem_App_asp_ebay_shipping_ApacShippingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddAPACShippingPackageCompletedEventHandler AddAPACShippingPackageCompleted;
        
        /// <remarks/>
        public event CancelAPACShippingPackageCompletedEventHandler CancelAPACShippingPackageCompleted;
        
        /// <remarks/>
        public event ConfirmAPACShippingPackageCompletedEventHandler ConfirmAPACShippingPackageCompleted;
        
        /// <remarks/>
        public event GetAPACShippingLabelCompletedEventHandler GetAPACShippingLabelCompleted;
        
        /// <remarks/>
        public event GetAPACShippingLabelsCompletedEventHandler GetAPACShippingLabelsCompleted;
        
        /// <remarks/>
        public event GetAPACShippingPackageCompletedEventHandler GetAPACShippingPackageCompleted;
        
        /// <remarks/>
        public event GetAPACShippingPackageStatusCompletedEventHandler GetAPACShippingPackageStatusCompleted;
        
        /// <remarks/>
        public event GetAPACShippingRateCompletedEventHandler GetAPACShippingRateCompleted;
        
        /// <remarks/>
        public event VerifyAPACShippingUserCompletedEventHandler VerifyAPACShippingUserCompleted;
        
        /// <remarks/>
        public event RecreateAPACShippingPackageCompletedEventHandler RecreateAPACShippingPackageCompleted;
        
        /// <remarks/>
        public event GetAPACShippingTrackCodeCompletedEventHandler GetAPACShippingTrackCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/AddAPACShippingPackage", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddAPACShippingPackageResponse AddAPACShippingPackage(AddAPACShippingPackageRequest AddAPACShippingPackageRequest) {
            object[] results = this.Invoke("AddAPACShippingPackage", new object[] {
                        AddAPACShippingPackageRequest});
            return ((AddAPACShippingPackageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddAPACShippingPackageAsync(AddAPACShippingPackageRequest AddAPACShippingPackageRequest) {
            this.AddAPACShippingPackageAsync(AddAPACShippingPackageRequest, null);
        }
        
        /// <remarks/>
        public void AddAPACShippingPackageAsync(AddAPACShippingPackageRequest AddAPACShippingPackageRequest, object userState) {
            if ((this.AddAPACShippingPackageOperationCompleted == null)) {
                this.AddAPACShippingPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAPACShippingPackageOperationCompleted);
            }
            this.InvokeAsync("AddAPACShippingPackage", new object[] {
                        AddAPACShippingPackageRequest}, this.AddAPACShippingPackageOperationCompleted, userState);
        }
        
        private void OnAddAPACShippingPackageOperationCompleted(object arg) {
            if ((this.AddAPACShippingPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAPACShippingPackageCompleted(this, new AddAPACShippingPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/CancelAPACShippingPackage", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CancelAPACShippingPackageResponse CancelAPACShippingPackage(CancelAPACShippingPackageRequest CancelAPACShippingPackageRequest) {
            object[] results = this.Invoke("CancelAPACShippingPackage", new object[] {
                        CancelAPACShippingPackageRequest});
            return ((CancelAPACShippingPackageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CancelAPACShippingPackageAsync(CancelAPACShippingPackageRequest CancelAPACShippingPackageRequest) {
            this.CancelAPACShippingPackageAsync(CancelAPACShippingPackageRequest, null);
        }
        
        /// <remarks/>
        public void CancelAPACShippingPackageAsync(CancelAPACShippingPackageRequest CancelAPACShippingPackageRequest, object userState) {
            if ((this.CancelAPACShippingPackageOperationCompleted == null)) {
                this.CancelAPACShippingPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelAPACShippingPackageOperationCompleted);
            }
            this.InvokeAsync("CancelAPACShippingPackage", new object[] {
                        CancelAPACShippingPackageRequest}, this.CancelAPACShippingPackageOperationCompleted, userState);
        }
        
        private void OnCancelAPACShippingPackageOperationCompleted(object arg) {
            if ((this.CancelAPACShippingPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelAPACShippingPackageCompleted(this, new CancelAPACShippingPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/ConfirmAPACShippingPackage", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConfirmAPACShippingPackageResponse ConfirmAPACShippingPackage(ConfirmAPACShippingPackageRequest ConfirmAPACShippingPackageRequest) {
            object[] results = this.Invoke("ConfirmAPACShippingPackage", new object[] {
                        ConfirmAPACShippingPackageRequest});
            return ((ConfirmAPACShippingPackageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmAPACShippingPackageAsync(ConfirmAPACShippingPackageRequest ConfirmAPACShippingPackageRequest) {
            this.ConfirmAPACShippingPackageAsync(ConfirmAPACShippingPackageRequest, null);
        }
        
        /// <remarks/>
        public void ConfirmAPACShippingPackageAsync(ConfirmAPACShippingPackageRequest ConfirmAPACShippingPackageRequest, object userState) {
            if ((this.ConfirmAPACShippingPackageOperationCompleted == null)) {
                this.ConfirmAPACShippingPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmAPACShippingPackageOperationCompleted);
            }
            this.InvokeAsync("ConfirmAPACShippingPackage", new object[] {
                        ConfirmAPACShippingPackageRequest}, this.ConfirmAPACShippingPackageOperationCompleted, userState);
        }
        
        private void OnConfirmAPACShippingPackageOperationCompleted(object arg) {
            if ((this.ConfirmAPACShippingPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmAPACShippingPackageCompleted(this, new ConfirmAPACShippingPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/GetAPACShippingLabel", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetAPACShippingLabelResponse GetAPACShippingLabel(GetAPACShippingLabelRequest GetAPACShippingLabelRequest) {
            object[] results = this.Invoke("GetAPACShippingLabel", new object[] {
                        GetAPACShippingLabelRequest});
            return ((GetAPACShippingLabelResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAPACShippingLabelAsync(GetAPACShippingLabelRequest GetAPACShippingLabelRequest) {
            this.GetAPACShippingLabelAsync(GetAPACShippingLabelRequest, null);
        }
        
        /// <remarks/>
        public void GetAPACShippingLabelAsync(GetAPACShippingLabelRequest GetAPACShippingLabelRequest, object userState) {
            if ((this.GetAPACShippingLabelOperationCompleted == null)) {
                this.GetAPACShippingLabelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAPACShippingLabelOperationCompleted);
            }
            this.InvokeAsync("GetAPACShippingLabel", new object[] {
                        GetAPACShippingLabelRequest}, this.GetAPACShippingLabelOperationCompleted, userState);
        }
        
        private void OnGetAPACShippingLabelOperationCompleted(object arg) {
            if ((this.GetAPACShippingLabelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAPACShippingLabelCompleted(this, new GetAPACShippingLabelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/GetAPACShippingLabels", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetAPACShippingLabelsResponse GetAPACShippingLabels(GetAPACShippingLabelsRequest GetAPACShippingLabelRequest) {
            object[] results = this.Invoke("GetAPACShippingLabels", new object[] {
                        GetAPACShippingLabelRequest});
            return ((GetAPACShippingLabelsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAPACShippingLabelsAsync(GetAPACShippingLabelsRequest GetAPACShippingLabelRequest) {
            this.GetAPACShippingLabelsAsync(GetAPACShippingLabelRequest, null);
        }
        
        /// <remarks/>
        public void GetAPACShippingLabelsAsync(GetAPACShippingLabelsRequest GetAPACShippingLabelRequest, object userState) {
            if ((this.GetAPACShippingLabelsOperationCompleted == null)) {
                this.GetAPACShippingLabelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAPACShippingLabelsOperationCompleted);
            }
            this.InvokeAsync("GetAPACShippingLabels", new object[] {
                        GetAPACShippingLabelRequest}, this.GetAPACShippingLabelsOperationCompleted, userState);
        }
        
        private void OnGetAPACShippingLabelsOperationCompleted(object arg) {
            if ((this.GetAPACShippingLabelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAPACShippingLabelsCompleted(this, new GetAPACShippingLabelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/GetAPACShippingPackage", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetAPACShippingPackageResponse GetAPACShippingPackage(GetAPACShippingPackageRequest GetAPACShippingPackageRequest) {
            object[] results = this.Invoke("GetAPACShippingPackage", new object[] {
                        GetAPACShippingPackageRequest});
            return ((GetAPACShippingPackageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAPACShippingPackageAsync(GetAPACShippingPackageRequest GetAPACShippingPackageRequest) {
            this.GetAPACShippingPackageAsync(GetAPACShippingPackageRequest, null);
        }
        
        /// <remarks/>
        public void GetAPACShippingPackageAsync(GetAPACShippingPackageRequest GetAPACShippingPackageRequest, object userState) {
            if ((this.GetAPACShippingPackageOperationCompleted == null)) {
                this.GetAPACShippingPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAPACShippingPackageOperationCompleted);
            }
            this.InvokeAsync("GetAPACShippingPackage", new object[] {
                        GetAPACShippingPackageRequest}, this.GetAPACShippingPackageOperationCompleted, userState);
        }
        
        private void OnGetAPACShippingPackageOperationCompleted(object arg) {
            if ((this.GetAPACShippingPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAPACShippingPackageCompleted(this, new GetAPACShippingPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/GetAPACShippingPackageStatus", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetAPACShippingPackageStatusResponse GetAPACShippingPackageStatus(GetAPACShippingPackageStatusRequest GetAPACShippingPackageStatusRequest) {
            object[] results = this.Invoke("GetAPACShippingPackageStatus", new object[] {
                        GetAPACShippingPackageStatusRequest});
            return ((GetAPACShippingPackageStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAPACShippingPackageStatusAsync(GetAPACShippingPackageStatusRequest GetAPACShippingPackageStatusRequest) {
            this.GetAPACShippingPackageStatusAsync(GetAPACShippingPackageStatusRequest, null);
        }
        
        /// <remarks/>
        public void GetAPACShippingPackageStatusAsync(GetAPACShippingPackageStatusRequest GetAPACShippingPackageStatusRequest, object userState) {
            if ((this.GetAPACShippingPackageStatusOperationCompleted == null)) {
                this.GetAPACShippingPackageStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAPACShippingPackageStatusOperationCompleted);
            }
            this.InvokeAsync("GetAPACShippingPackageStatus", new object[] {
                        GetAPACShippingPackageStatusRequest}, this.GetAPACShippingPackageStatusOperationCompleted, userState);
        }
        
        private void OnGetAPACShippingPackageStatusOperationCompleted(object arg) {
            if ((this.GetAPACShippingPackageStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAPACShippingPackageStatusCompleted(this, new GetAPACShippingPackageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/GetAPACShippingRate", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetAPACShippingRateResponse GetAPACShippingRate(GetAPACShippingRateRequest GetAPACShippingRateRequest) {
            object[] results = this.Invoke("GetAPACShippingRate", new object[] {
                        GetAPACShippingRateRequest});
            return ((GetAPACShippingRateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAPACShippingRateAsync(GetAPACShippingRateRequest GetAPACShippingRateRequest) {
            this.GetAPACShippingRateAsync(GetAPACShippingRateRequest, null);
        }
        
        /// <remarks/>
        public void GetAPACShippingRateAsync(GetAPACShippingRateRequest GetAPACShippingRateRequest, object userState) {
            if ((this.GetAPACShippingRateOperationCompleted == null)) {
                this.GetAPACShippingRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAPACShippingRateOperationCompleted);
            }
            this.InvokeAsync("GetAPACShippingRate", new object[] {
                        GetAPACShippingRateRequest}, this.GetAPACShippingRateOperationCompleted, userState);
        }
        
        private void OnGetAPACShippingRateOperationCompleted(object arg) {
            if ((this.GetAPACShippingRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAPACShippingRateCompleted(this, new GetAPACShippingRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/VerifyAPACShippingUser", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VerifyAPACShippingUserResponse VerifyAPACShippingUser(VerifyAPACShippingUserRequest VerifyAPACShippingUserRequest) {
            object[] results = this.Invoke("VerifyAPACShippingUser", new object[] {
                        VerifyAPACShippingUserRequest});
            return ((VerifyAPACShippingUserResponse)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyAPACShippingUserAsync(VerifyAPACShippingUserRequest VerifyAPACShippingUserRequest) {
            this.VerifyAPACShippingUserAsync(VerifyAPACShippingUserRequest, null);
        }
        
        /// <remarks/>
        public void VerifyAPACShippingUserAsync(VerifyAPACShippingUserRequest VerifyAPACShippingUserRequest, object userState) {
            if ((this.VerifyAPACShippingUserOperationCompleted == null)) {
                this.VerifyAPACShippingUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyAPACShippingUserOperationCompleted);
            }
            this.InvokeAsync("VerifyAPACShippingUser", new object[] {
                        VerifyAPACShippingUserRequest}, this.VerifyAPACShippingUserOperationCompleted, userState);
        }
        
        private void OnVerifyAPACShippingUserOperationCompleted(object arg) {
            if ((this.VerifyAPACShippingUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyAPACShippingUserCompleted(this, new VerifyAPACShippingUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/RecreateAPACShippingPackage", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RecreateAPACShippingPackageResponse RecreateAPACShippingPackage(RecreateAPACShippingPackageRequest RecreateAPACShippingPackageRequest) {
            object[] results = this.Invoke("RecreateAPACShippingPackage", new object[] {
                        RecreateAPACShippingPackageRequest});
            return ((RecreateAPACShippingPackageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RecreateAPACShippingPackageAsync(RecreateAPACShippingPackageRequest RecreateAPACShippingPackageRequest) {
            this.RecreateAPACShippingPackageAsync(RecreateAPACShippingPackageRequest, null);
        }
        
        /// <remarks/>
        public void RecreateAPACShippingPackageAsync(RecreateAPACShippingPackageRequest RecreateAPACShippingPackageRequest, object userState) {
            if ((this.RecreateAPACShippingPackageOperationCompleted == null)) {
                this.RecreateAPACShippingPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecreateAPACShippingPackageOperationCompleted);
            }
            this.InvokeAsync("RecreateAPACShippingPackage", new object[] {
                        RecreateAPACShippingPackageRequest}, this.RecreateAPACShippingPackageOperationCompleted, userState);
        }
        
        private void OnRecreateAPACShippingPackageOperationCompleted(object arg) {
            if ((this.RecreateAPACShippingPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecreateAPACShippingPackageCompleted(this, new RecreateAPACShippingPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.apacshipping.ebay.com/GetAPACShippingTrackCode", RequestNamespace="http://api.apacshipping.ebay.com/", ResponseNamespace="http://api.apacshipping.ebay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetAPACShippingTrackCodeResponse GetAPACShippingTrackCode(GetAPACShippingTrackCodeRequest GetAPACShippingTrackCodeRequest) {
            object[] results = this.Invoke("GetAPACShippingTrackCode", new object[] {
                        GetAPACShippingTrackCodeRequest});
            return ((GetAPACShippingTrackCodeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAPACShippingTrackCodeAsync(GetAPACShippingTrackCodeRequest GetAPACShippingTrackCodeRequest) {
            this.GetAPACShippingTrackCodeAsync(GetAPACShippingTrackCodeRequest, null);
        }
        
        /// <remarks/>
        public void GetAPACShippingTrackCodeAsync(GetAPACShippingTrackCodeRequest GetAPACShippingTrackCodeRequest, object userState) {
            if ((this.GetAPACShippingTrackCodeOperationCompleted == null)) {
                this.GetAPACShippingTrackCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAPACShippingTrackCodeOperationCompleted);
            }
            this.InvokeAsync("GetAPACShippingTrackCode", new object[] {
                        GetAPACShippingTrackCodeRequest}, this.GetAPACShippingTrackCodeOperationCompleted, userState);
        }
        
        private void OnGetAPACShippingTrackCodeOperationCompleted(object arg) {
            if ((this.GetAPACShippingTrackCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAPACShippingTrackCodeCompleted(this, new GetAPACShippingTrackCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class AddAPACShippingPackageRequest : BaseRequest {
        
        private OrderDetail orderDetailField;
        
        private string serviceField;
        
        /// <remarks/>
        public OrderDetail OrderDetail {
            get {
                return this.orderDetailField;
            }
            set {
                this.orderDetailField = value;
            }
        }
        
        /// <remarks/>
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class OrderDetail {
        
        private PickUpAddress pickUpAddressField;
        
        private ShipFromAddress shipFromAddressField;
        
        private ShipToAddress shipToAddressField;
        
        private Item[] itemListField;
        
        private int eMSPickUpTypeField;
        
        private ReturnAddress returnAddressField;
        
        private string externalRefIdField;
        
        private ShippingPackage shippingPackageField;
        
        /// <remarks/>
        public PickUpAddress PickUpAddress {
            get {
                return this.pickUpAddressField;
            }
            set {
                this.pickUpAddressField = value;
            }
        }
        
        /// <remarks/>
        public ShipFromAddress ShipFromAddress {
            get {
                return this.shipFromAddressField;
            }
            set {
                this.shipFromAddressField = value;
            }
        }
        
        /// <remarks/>
        public ShipToAddress ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Item[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
        
        /// <remarks/>
        public int EMSPickUpType {
            get {
                return this.eMSPickUpTypeField;
            }
            set {
                this.eMSPickUpTypeField = value;
            }
        }
        
        /// <remarks/>
        public ReturnAddress ReturnAddress {
            get {
                return this.returnAddressField;
            }
            set {
                this.returnAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalRefId {
            get {
                return this.externalRefIdField;
            }
            set {
                this.externalRefIdField = value;
            }
        }
        
        /// <remarks/>
        public ShippingPackage ShippingPackage {
            get {
                return this.shippingPackageField;
            }
            set {
                this.shippingPackageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class PickUpAddress : Address {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShipToAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShipFromAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PickUpAddress))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class Address {
        
        private string contactField;
        
        private string companyField;
        
        private string streetField;
        
        private string districtField;
        
        private string cityField;
        
        private string provinceField;
        
        private string countryCodeField;
        
        private string postcodeField;
        
        private string phoneField;
        
        private string mobileField;
        
        private string emailField;
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class CarrierGeo {
        
        private string carrierField;
        
        private string fromCountryCodeField;
        
        /// <remarks/>
        public string Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        public string FromCountryCode {
            get {
                return this.fromCountryCodeField;
            }
            set {
                this.fromCountryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class Notification {
        
        private EnumSeverity severityField;
        
        private bool severityFieldSpecified;
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public EnumSeverity Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeveritySpecified {
            get {
                return this.severityFieldSpecified;
            }
            set {
                this.severityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public enum EnumSeverity {
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        PartialFailure,
        
        /// <remarks/>
        Warning,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingTrackCodeResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecreateAPACShippingPackageResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerifyAPACShippingUserResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingRateResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingPackageStatusResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingPackageResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingLabelsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingLabelResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfirmAPACShippingPackageResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelAPACShippingPackageResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddAPACShippingPackageResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class BaseResponse {
        
        private string versionField;
        
        private EnumAck ackField;
        
        private string messageField;
        
        private Notification[] notificationListField;
        
        private System.DateTime timestampField;
        
        private string invocationIDField;
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public EnumAck Ack {
            get {
                return this.ackField;
            }
            set {
                this.ackField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Notification[] NotificationList {
            get {
                return this.notificationListField;
            }
            set {
                this.notificationListField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public string InvocationID {
            get {
                return this.invocationIDField;
            }
            set {
                this.invocationIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public enum EnumAck {
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        PartialFailure,
        
        /// <remarks/>
        Warning,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingTrackCodeResponse : BaseResponse {
        
        private string trackCodeField;
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class RecreateAPACShippingPackageResponse : BaseResponse {
        
        private string trackCodeField;
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class VerifyAPACShippingUserResponse : BaseResponse {
        
        private CarrierGeo[] carrierListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CarrierGeo[] CarrierList {
            get {
                return this.carrierListField;
            }
            set {
                this.carrierListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingRateResponse : BaseResponse {
        
        private decimal deliveryChargeField;
        
        private decimal additionalChargeField;
        
        private decimal insuranceFeeField;
        
        private decimal taxesField;
        
        private decimal dutiesAndTaxesField;
        
        private string currencyField;
        
        /// <remarks/>
        public decimal DeliveryCharge {
            get {
                return this.deliveryChargeField;
            }
            set {
                this.deliveryChargeField = value;
            }
        }
        
        /// <remarks/>
        public decimal AdditionalCharge {
            get {
                return this.additionalChargeField;
            }
            set {
                this.additionalChargeField = value;
            }
        }
        
        /// <remarks/>
        public decimal InsuranceFee {
            get {
                return this.insuranceFeeField;
            }
            set {
                this.insuranceFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Taxes {
            get {
                return this.taxesField;
            }
            set {
                this.taxesField = value;
            }
        }
        
        /// <remarks/>
        public decimal DutiesAndTaxes {
            get {
                return this.dutiesAndTaxesField;
            }
            set {
                this.dutiesAndTaxesField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingPackageStatusResponse : BaseResponse {
        
        private int statusField;
        
        private string noteField;
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingPackageResponse : BaseResponse {
        
        private string carrierField;
        
        private string serviceField;
        
        private OrderDetail orderDetailField;
        
        /// <remarks/>
        public string Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        public OrderDetail OrderDetail {
            get {
                return this.orderDetailField;
            }
            set {
                this.orderDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingLabelsResponse : BaseResponse {
        
        private byte[] labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingLabelResponse : BaseResponse {
        
        private byte[] labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class ConfirmAPACShippingPackageResponse : BaseResponse {
        
        private string carrierConfirmIdField;
        
        private System.DateTime pickUpConfirmedDateTimeField;
        
        private bool pickUpConfirmedDateTimeFieldSpecified;
        
        /// <remarks/>
        public string CarrierConfirmId {
            get {
                return this.carrierConfirmIdField;
            }
            set {
                this.carrierConfirmIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PickUpConfirmedDateTime {
            get {
                return this.pickUpConfirmedDateTimeField;
            }
            set {
                this.pickUpConfirmedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickUpConfirmedDateTimeSpecified {
            get {
                return this.pickUpConfirmedDateTimeFieldSpecified;
            }
            set {
                this.pickUpConfirmedDateTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class CancelAPACShippingPackageResponse : BaseResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class AddAPACShippingPackageResponse : BaseResponse {
        
        private string trackCodeField;
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class ShippingPackage {
        
        private string descriptionField;
        
        private double lengthField;
        
        private double heightField;
        
        private double widthField;
        
        private string collectionInstructionsField;
        
        private string deliveryInstructionsField;
        
        private string incotermsField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public double Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public string CollectionInstructions {
            get {
                return this.collectionInstructionsField;
            }
            set {
                this.collectionInstructionsField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryInstructions {
            get {
                return this.deliveryInstructionsField;
            }
            set {
                this.deliveryInstructionsField = value;
            }
        }
        
        /// <remarks/>
        public string Incoterms {
            get {
                return this.incotermsField;
            }
            set {
                this.incotermsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class SKU {
        
        private string sKUIDField;
        
        private decimal weightField;
        
        private string customsTitleField;
        
        private string customsTitleENField;
        
        private decimal declaredValueField;
        
        private string originCountryNameField;
        
        private string originCountryCodeField;
        
        private string hTSNumberField;
        
        /// <remarks/>
        public string SKUID {
            get {
                return this.sKUIDField;
            }
            set {
                this.sKUIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public string CustomsTitle {
            get {
                return this.customsTitleField;
            }
            set {
                this.customsTitleField = value;
            }
        }
        
        /// <remarks/>
        public string CustomsTitleEN {
            get {
                return this.customsTitleENField;
            }
            set {
                this.customsTitleENField = value;
            }
        }
        
        /// <remarks/>
        public decimal DeclaredValue {
            get {
                return this.declaredValueField;
            }
            set {
                this.declaredValueField = value;
            }
        }
        
        /// <remarks/>
        public string OriginCountryName {
            get {
                return this.originCountryNameField;
            }
            set {
                this.originCountryNameField = value;
            }
        }
        
        /// <remarks/>
        public string OriginCountryCode {
            get {
                return this.originCountryCodeField;
            }
            set {
                this.originCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HTSNumber {
            get {
                return this.hTSNumberField;
            }
            set {
                this.hTSNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class Item {
        
        private string currencyCodeField;
        
        private string eBayEmailField;
        
        private string eBayBuyerIDField;
        
        private string eBayItemIDField;
        
        private string eBayItemTitleField;
        
        private string eBayMessageField;
        
        private int eBaySiteIDField;
        
        private string eBayTransactionIDField;
        
        private string eBayOrderIDField;
        
        private string noteField;
        
        private int orderSalesRecordNumberField;
        
        private System.DateTime paymentDateField;
        
        private string payPalEmailField;
        
        private string payPalMessageField;
        
        private int postedQTYField;
        
        private decimal receivedAmountField;
        
        private int salesRecordNumberField;
        
        private System.DateTime soldDateField;
        
        private decimal soldPriceField;
        
        private int soldQTYField;
        
        private SKU sKUField;
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EBayEmail {
            get {
                return this.eBayEmailField;
            }
            set {
                this.eBayEmailField = value;
            }
        }
        
        /// <remarks/>
        public string EBayBuyerID {
            get {
                return this.eBayBuyerIDField;
            }
            set {
                this.eBayBuyerIDField = value;
            }
        }
        
        /// <remarks/>
        public string EBayItemID {
            get {
                return this.eBayItemIDField;
            }
            set {
                this.eBayItemIDField = value;
            }
        }
        
        /// <remarks/>
        public string EBayItemTitle {
            get {
                return this.eBayItemTitleField;
            }
            set {
                this.eBayItemTitleField = value;
            }
        }
        
        /// <remarks/>
        public string EBayMessage {
            get {
                return this.eBayMessageField;
            }
            set {
                this.eBayMessageField = value;
            }
        }
        
        /// <remarks/>
        public int EBaySiteID {
            get {
                return this.eBaySiteIDField;
            }
            set {
                this.eBaySiteIDField = value;
            }
        }
        
        /// <remarks/>
        public string EBayTransactionID {
            get {
                return this.eBayTransactionIDField;
            }
            set {
                this.eBayTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string EBayOrderID {
            get {
                return this.eBayOrderIDField;
            }
            set {
                this.eBayOrderIDField = value;
            }
        }
        
        /// <remarks/>
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public int OrderSalesRecordNumber {
            get {
                return this.orderSalesRecordNumberField;
            }
            set {
                this.orderSalesRecordNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string PayPalEmail {
            get {
                return this.payPalEmailField;
            }
            set {
                this.payPalEmailField = value;
            }
        }
        
        /// <remarks/>
        public string PayPalMessage {
            get {
                return this.payPalMessageField;
            }
            set {
                this.payPalMessageField = value;
            }
        }
        
        /// <remarks/>
        public int PostedQTY {
            get {
                return this.postedQTYField;
            }
            set {
                this.postedQTYField = value;
            }
        }
        
        /// <remarks/>
        public decimal ReceivedAmount {
            get {
                return this.receivedAmountField;
            }
            set {
                this.receivedAmountField = value;
            }
        }
        
        /// <remarks/>
        public int SalesRecordNumber {
            get {
                return this.salesRecordNumberField;
            }
            set {
                this.salesRecordNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SoldDate {
            get {
                return this.soldDateField;
            }
            set {
                this.soldDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal SoldPrice {
            get {
                return this.soldPriceField;
            }
            set {
                this.soldPriceField = value;
            }
        }
        
        /// <remarks/>
        public int SoldQTY {
            get {
                return this.soldQTYField;
            }
            set {
                this.soldQTYField = value;
            }
        }
        
        /// <remarks/>
        public SKU SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingTrackCodeRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecreateAPACShippingPackageRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerifyAPACShippingUserRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingRateRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingPackageStatusRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingPackageRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingLabelsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAPACShippingLabelRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfirmAPACShippingPackageRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelAPACShippingPackageRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddAPACShippingPackageRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class BaseRequest {
        
        private string versionField;
        
        private string aPIDevUserIDField;
        
        private string aPISellerUserTokenField;
        
        private string appIDField;
        
        private string appCertField;
        
        private string aPISellerUserIDField;
        
        private string messageIDField;
        
        private string carrierField;
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string APIDevUserID {
            get {
                return this.aPIDevUserIDField;
            }
            set {
                this.aPIDevUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string APISellerUserToken {
            get {
                return this.aPISellerUserTokenField;
            }
            set {
                this.aPISellerUserTokenField = value;
            }
        }
        
        /// <remarks/>
        public string AppID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        public string AppCert {
            get {
                return this.appCertField;
            }
            set {
                this.appCertField = value;
            }
        }
        
        /// <remarks/>
        public string APISellerUserID {
            get {
                return this.aPISellerUserIDField;
            }
            set {
                this.aPISellerUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingTrackCodeRequest : BaseRequest {
        
        private string eBayItemIDField;
        
        private string eBayTransactionIDField;
        
        /// <remarks/>
        public string EBayItemID {
            get {
                return this.eBayItemIDField;
            }
            set {
                this.eBayItemIDField = value;
            }
        }
        
        /// <remarks/>
        public string EBayTransactionID {
            get {
                return this.eBayTransactionIDField;
            }
            set {
                this.eBayTransactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class RecreateAPACShippingPackageRequest : BaseRequest {
        
        private string trackCodeField;
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class VerifyAPACShippingUserRequest : BaseRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingRateRequest : BaseRequest {
        
        private string serviceField;
        
        private Address fromAddressField;
        
        private ShipToAddress shipToAddressField;
        
        private int eMSPickUpTypeField;
        
        private bool eMSPickUpTypeFieldSpecified;
        
        private decimal weightField;
        
        private double lengthField;
        
        private double heightField;
        
        private double widthField;
        
        private int insuranceTypeField;
        
        private decimal insuranceAmountField;
        
        private int mailTypeField;
        
        /// <remarks/>
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        public Address FromAddress {
            get {
                return this.fromAddressField;
            }
            set {
                this.fromAddressField = value;
            }
        }
        
        /// <remarks/>
        public ShipToAddress ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public int EMSPickUpType {
            get {
                return this.eMSPickUpTypeField;
            }
            set {
                this.eMSPickUpTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMSPickUpTypeSpecified {
            get {
                return this.eMSPickUpTypeFieldSpecified;
            }
            set {
                this.eMSPickUpTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public double Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public double Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int InsuranceType {
            get {
                return this.insuranceTypeField;
            }
            set {
                this.insuranceTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal InsuranceAmount {
            get {
                return this.insuranceAmountField;
            }
            set {
                this.insuranceAmountField = value;
            }
        }
        
        /// <remarks/>
        public int MailType {
            get {
                return this.mailTypeField;
            }
            set {
                this.mailTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class ShipToAddress : Address {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingPackageStatusRequest : BaseRequest {
        
        private string trackCodeField;
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingPackageRequest : BaseRequest {
        
        private string trackCodeField;
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingLabelsRequest : BaseRequest {
        
        private string[] trackCodeListField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TrackCode", IsNullable=false)]
        public string[] TrackCodeList {
            get {
                return this.trackCodeListField;
            }
            set {
                this.trackCodeListField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class GetAPACShippingLabelRequest : BaseRequest {
        
        private string trackCodeField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class ConfirmAPACShippingPackageRequest : BaseRequest {
        
        private string trackCodeField;
        
        private System.DateTime pickUpRequestDateTimeField;
        
        private bool pickUpRequestDateTimeFieldSpecified;
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PickUpRequestDateTime {
            get {
                return this.pickUpRequestDateTimeField;
            }
            set {
                this.pickUpRequestDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickUpRequestDateTimeSpecified {
            get {
                return this.pickUpRequestDateTimeFieldSpecified;
            }
            set {
                this.pickUpRequestDateTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class CancelAPACShippingPackageRequest : BaseRequest {
        
        private string trackCodeField;
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class ReturnAddress : Address {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.apacshipping.ebay.com/")]
    public partial class ShipFromAddress : Address {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void AddAPACShippingPackageCompletedEventHandler(object sender, AddAPACShippingPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAPACShippingPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAPACShippingPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddAPACShippingPackageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddAPACShippingPackageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CancelAPACShippingPackageCompletedEventHandler(object sender, CancelAPACShippingPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelAPACShippingPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelAPACShippingPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelAPACShippingPackageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelAPACShippingPackageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ConfirmAPACShippingPackageCompletedEventHandler(object sender, ConfirmAPACShippingPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmAPACShippingPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmAPACShippingPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfirmAPACShippingPackageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmAPACShippingPackageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAPACShippingLabelCompletedEventHandler(object sender, GetAPACShippingLabelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAPACShippingLabelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAPACShippingLabelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAPACShippingLabelResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAPACShippingLabelResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAPACShippingLabelsCompletedEventHandler(object sender, GetAPACShippingLabelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAPACShippingLabelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAPACShippingLabelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAPACShippingLabelsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAPACShippingLabelsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAPACShippingPackageCompletedEventHandler(object sender, GetAPACShippingPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAPACShippingPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAPACShippingPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAPACShippingPackageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAPACShippingPackageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAPACShippingPackageStatusCompletedEventHandler(object sender, GetAPACShippingPackageStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAPACShippingPackageStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAPACShippingPackageStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAPACShippingPackageStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAPACShippingPackageStatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAPACShippingRateCompletedEventHandler(object sender, GetAPACShippingRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAPACShippingRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAPACShippingRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAPACShippingRateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAPACShippingRateResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void VerifyAPACShippingUserCompletedEventHandler(object sender, VerifyAPACShippingUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyAPACShippingUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyAPACShippingUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VerifyAPACShippingUserResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VerifyAPACShippingUserResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void RecreateAPACShippingPackageCompletedEventHandler(object sender, RecreateAPACShippingPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecreateAPACShippingPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecreateAPACShippingPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RecreateAPACShippingPackageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RecreateAPACShippingPackageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAPACShippingTrackCodeCompletedEventHandler(object sender, GetAPACShippingTrackCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAPACShippingTrackCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAPACShippingTrackCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAPACShippingTrackCodeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAPACShippingTrackCodeResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591