//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace DDX.OrderManagementSystem.App.com.bdt.post {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ParcelOprWebServiceSoapBinding", Namespace="http://cxf.pl/")]
    public partial class ParcelOprWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback forecastByRefNoServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryParcelShippingCostByTarckingNoServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteParcelByRefNoServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryParcelShippingCostByRefNoServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeShippingMethodByRefNoServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryShipTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryParcelServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryShipTypeZoningOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeShippingMethodServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryParcelByRefNoServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback forecastServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback addParcelServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteParcelByNoServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback addParcelAndForecastServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ParcelOprWebService() {
            this.Url = global::DDX.OrderManagementSystem.App.Properties.Settings.Default.DDX_OrderManagementSystem_App_com_bdt_post_ParcelOprWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event forecastByRefNoServiceCompletedEventHandler forecastByRefNoServiceCompleted;
        
        /// <remarks/>
        public event queryParcelShippingCostByTarckingNoServiceCompletedEventHandler queryParcelShippingCostByTarckingNoServiceCompleted;
        
        /// <remarks/>
        public event deleteParcelByRefNoServiceCompletedEventHandler deleteParcelByRefNoServiceCompleted;
        
        /// <remarks/>
        public event queryParcelShippingCostByRefNoServiceCompletedEventHandler queryParcelShippingCostByRefNoServiceCompleted;
        
        /// <remarks/>
        public event changeShippingMethodByRefNoServiceCompletedEventHandler changeShippingMethodByRefNoServiceCompleted;
        
        /// <remarks/>
        public event queryShipTypeCompletedEventHandler queryShipTypeCompleted;
        
        /// <remarks/>
        public event queryParcelServiceCompletedEventHandler queryParcelServiceCompleted;
        
        /// <remarks/>
        public event queryShipTypeZoningCompletedEventHandler queryShipTypeZoningCompleted;
        
        /// <remarks/>
        public event changeShippingMethodServiceCompletedEventHandler changeShippingMethodServiceCompleted;
        
        /// <remarks/>
        public event queryParcelByRefNoServiceCompletedEventHandler queryParcelByRefNoServiceCompleted;
        
        /// <remarks/>
        public event forecastServiceCompletedEventHandler forecastServiceCompleted;
        
        /// <remarks/>
        public event addParcelServiceCompletedEventHandler addParcelServiceCompleted;
        
        /// <remarks/>
        public event deleteParcelByNoServiceCompletedEventHandler deleteParcelByNoServiceCompleted;
        
        /// <remarks/>
        public event addParcelAndForecastServiceCompletedEventHandler addParcelAndForecastServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public returnObject[] forecastByRefNoService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] refNos) {
            object[] results = this.Invoke("forecastByRefNoService", new object[] {
                        companyID,
                        pwd,
                        refNos});
            return ((returnObject[])(results[0]));
        }
        
        /// <remarks/>
        public void forecastByRefNoServiceAsync(string companyID, string pwd, string[] refNos) {
            this.forecastByRefNoServiceAsync(companyID, pwd, refNos, null);
        }
        
        /// <remarks/>
        public void forecastByRefNoServiceAsync(string companyID, string pwd, string[] refNos, object userState) {
            if ((this.forecastByRefNoServiceOperationCompleted == null)) {
                this.forecastByRefNoServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnforecastByRefNoServiceOperationCompleted);
            }
            this.InvokeAsync("forecastByRefNoService", new object[] {
                        companyID,
                        pwd,
                        refNos}, this.forecastByRefNoServiceOperationCompleted, userState);
        }
        
        private void OnforecastByRefNoServiceOperationCompleted(object arg) {
            if ((this.forecastByRefNoServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.forecastByRefNoServiceCompleted(this, new forecastByRefNoServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public parcelShippingCost[] queryParcelShippingCostByTarckingNoService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] arg2) {
            object[] results = this.Invoke("queryParcelShippingCostByTarckingNoService", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((parcelShippingCost[])(results[0]));
        }
        
        /// <remarks/>
        public void queryParcelShippingCostByTarckingNoServiceAsync(string arg0, string arg1, string[] arg2) {
            this.queryParcelShippingCostByTarckingNoServiceAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void queryParcelShippingCostByTarckingNoServiceAsync(string arg0, string arg1, string[] arg2, object userState) {
            if ((this.queryParcelShippingCostByTarckingNoServiceOperationCompleted == null)) {
                this.queryParcelShippingCostByTarckingNoServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryParcelShippingCostByTarckingNoServiceOperationCompleted);
            }
            this.InvokeAsync("queryParcelShippingCostByTarckingNoService", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.queryParcelShippingCostByTarckingNoServiceOperationCompleted, userState);
        }
        
        private void OnqueryParcelShippingCostByTarckingNoServiceOperationCompleted(object arg) {
            if ((this.queryParcelShippingCostByTarckingNoServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryParcelShippingCostByTarckingNoServiceCompleted(this, new queryParcelShippingCostByTarckingNoServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public returnObject[] deleteParcelByRefNoService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] refNos) {
            object[] results = this.Invoke("deleteParcelByRefNoService", new object[] {
                        companyID,
                        pwd,
                        refNos});
            return ((returnObject[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteParcelByRefNoServiceAsync(string companyID, string pwd, string[] refNos) {
            this.deleteParcelByRefNoServiceAsync(companyID, pwd, refNos, null);
        }
        
        /// <remarks/>
        public void deleteParcelByRefNoServiceAsync(string companyID, string pwd, string[] refNos, object userState) {
            if ((this.deleteParcelByRefNoServiceOperationCompleted == null)) {
                this.deleteParcelByRefNoServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteParcelByRefNoServiceOperationCompleted);
            }
            this.InvokeAsync("deleteParcelByRefNoService", new object[] {
                        companyID,
                        pwd,
                        refNos}, this.deleteParcelByRefNoServiceOperationCompleted, userState);
        }
        
        private void OndeleteParcelByRefNoServiceOperationCompleted(object arg) {
            if ((this.deleteParcelByRefNoServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteParcelByRefNoServiceCompleted(this, new deleteParcelByRefNoServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public parcelShippingCost[] queryParcelShippingCostByRefNoService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] arg2) {
            object[] results = this.Invoke("queryParcelShippingCostByRefNoService", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((parcelShippingCost[])(results[0]));
        }
        
        /// <remarks/>
        public void queryParcelShippingCostByRefNoServiceAsync(string arg0, string arg1, string[] arg2) {
            this.queryParcelShippingCostByRefNoServiceAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void queryParcelShippingCostByRefNoServiceAsync(string arg0, string arg1, string[] arg2, object userState) {
            if ((this.queryParcelShippingCostByRefNoServiceOperationCompleted == null)) {
                this.queryParcelShippingCostByRefNoServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryParcelShippingCostByRefNoServiceOperationCompleted);
            }
            this.InvokeAsync("queryParcelShippingCostByRefNoService", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.queryParcelShippingCostByRefNoServiceOperationCompleted, userState);
        }
        
        private void OnqueryParcelShippingCostByRefNoServiceOperationCompleted(object arg) {
            if ((this.queryParcelShippingCostByRefNoServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryParcelShippingCostByRefNoServiceCompleted(this, new queryParcelShippingCostByRefNoServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public returnObject[] changeShippingMethodByRefNoService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] refNos, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] methods) {
            object[] results = this.Invoke("changeShippingMethodByRefNoService", new object[] {
                        companyID,
                        pwd,
                        refNos,
                        methods});
            return ((returnObject[])(results[0]));
        }
        
        /// <remarks/>
        public void changeShippingMethodByRefNoServiceAsync(string companyID, string pwd, string[] refNos, string[] methods) {
            this.changeShippingMethodByRefNoServiceAsync(companyID, pwd, refNos, methods, null);
        }
        
        /// <remarks/>
        public void changeShippingMethodByRefNoServiceAsync(string companyID, string pwd, string[] refNos, string[] methods, object userState) {
            if ((this.changeShippingMethodByRefNoServiceOperationCompleted == null)) {
                this.changeShippingMethodByRefNoServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeShippingMethodByRefNoServiceOperationCompleted);
            }
            this.InvokeAsync("changeShippingMethodByRefNoService", new object[] {
                        companyID,
                        pwd,
                        refNos,
                        methods}, this.changeShippingMethodByRefNoServiceOperationCompleted, userState);
        }
        
        private void OnchangeShippingMethodByRefNoServiceOperationCompleted(object arg) {
            if ((this.changeShippingMethodByRefNoServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeShippingMethodByRefNoServiceCompleted(this, new changeShippingMethodByRefNoServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public shipType[] queryShipType([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd) {
            object[] results = this.Invoke("queryShipType", new object[] {
                        companyID,
                        pwd});
            return ((shipType[])(results[0]));
        }
        
        /// <remarks/>
        public void queryShipTypeAsync(string companyID, string pwd) {
            this.queryShipTypeAsync(companyID, pwd, null);
        }
        
        /// <remarks/>
        public void queryShipTypeAsync(string companyID, string pwd, object userState) {
            if ((this.queryShipTypeOperationCompleted == null)) {
                this.queryShipTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryShipTypeOperationCompleted);
            }
            this.InvokeAsync("queryShipType", new object[] {
                        companyID,
                        pwd}, this.queryShipTypeOperationCompleted, userState);
        }
        
        private void OnqueryShipTypeOperationCompleted(object arg) {
            if ((this.queryShipTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryShipTypeCompleted(this, new queryShipTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public parcel[] queryParcelService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] vsnumbers) {
            object[] results = this.Invoke("queryParcelService", new object[] {
                        companyID,
                        pwd,
                        vsnumbers});
            return ((parcel[])(results[0]));
        }
        
        /// <remarks/>
        public void queryParcelServiceAsync(string companyID, string pwd, string[] vsnumbers) {
            this.queryParcelServiceAsync(companyID, pwd, vsnumbers, null);
        }
        
        /// <remarks/>
        public void queryParcelServiceAsync(string companyID, string pwd, string[] vsnumbers, object userState) {
            if ((this.queryParcelServiceOperationCompleted == null)) {
                this.queryParcelServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryParcelServiceOperationCompleted);
            }
            this.InvokeAsync("queryParcelService", new object[] {
                        companyID,
                        pwd,
                        vsnumbers}, this.queryParcelServiceOperationCompleted, userState);
        }
        
        private void OnqueryParcelServiceOperationCompleted(object arg) {
            if ((this.queryParcelServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryParcelServiceCompleted(this, new queryParcelServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public shipTypeZoning[] queryShipTypeZoning([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string shipCode) {
            object[] results = this.Invoke("queryShipTypeZoning", new object[] {
                        companyID,
                        pwd,
                        shipCode});
            return ((shipTypeZoning[])(results[0]));
        }
        
        /// <remarks/>
        public void queryShipTypeZoningAsync(string companyID, string pwd, string shipCode) {
            this.queryShipTypeZoningAsync(companyID, pwd, shipCode, null);
        }
        
        /// <remarks/>
        public void queryShipTypeZoningAsync(string companyID, string pwd, string shipCode, object userState) {
            if ((this.queryShipTypeZoningOperationCompleted == null)) {
                this.queryShipTypeZoningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryShipTypeZoningOperationCompleted);
            }
            this.InvokeAsync("queryShipTypeZoning", new object[] {
                        companyID,
                        pwd,
                        shipCode}, this.queryShipTypeZoningOperationCompleted, userState);
        }
        
        private void OnqueryShipTypeZoningOperationCompleted(object arg) {
            if ((this.queryShipTypeZoningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryShipTypeZoningCompleted(this, new queryShipTypeZoningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public returnObject[] changeShippingMethodService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] vsnumbers, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] methods) {
            object[] results = this.Invoke("changeShippingMethodService", new object[] {
                        companyID,
                        pwd,
                        vsnumbers,
                        methods});
            return ((returnObject[])(results[0]));
        }
        
        /// <remarks/>
        public void changeShippingMethodServiceAsync(string companyID, string pwd, string[] vsnumbers, string[] methods) {
            this.changeShippingMethodServiceAsync(companyID, pwd, vsnumbers, methods, null);
        }
        
        /// <remarks/>
        public void changeShippingMethodServiceAsync(string companyID, string pwd, string[] vsnumbers, string[] methods, object userState) {
            if ((this.changeShippingMethodServiceOperationCompleted == null)) {
                this.changeShippingMethodServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeShippingMethodServiceOperationCompleted);
            }
            this.InvokeAsync("changeShippingMethodService", new object[] {
                        companyID,
                        pwd,
                        vsnumbers,
                        methods}, this.changeShippingMethodServiceOperationCompleted, userState);
        }
        
        private void OnchangeShippingMethodServiceOperationCompleted(object arg) {
            if ((this.changeShippingMethodServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeShippingMethodServiceCompleted(this, new changeShippingMethodServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public parcel[] queryParcelByRefNoService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] refNos) {
            object[] results = this.Invoke("queryParcelByRefNoService", new object[] {
                        companyID,
                        pwd,
                        refNos});
            return ((parcel[])(results[0]));
        }
        
        /// <remarks/>
        public void queryParcelByRefNoServiceAsync(string companyID, string pwd, string[] refNos) {
            this.queryParcelByRefNoServiceAsync(companyID, pwd, refNos, null);
        }
        
        /// <remarks/>
        public void queryParcelByRefNoServiceAsync(string companyID, string pwd, string[] refNos, object userState) {
            if ((this.queryParcelByRefNoServiceOperationCompleted == null)) {
                this.queryParcelByRefNoServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryParcelByRefNoServiceOperationCompleted);
            }
            this.InvokeAsync("queryParcelByRefNoService", new object[] {
                        companyID,
                        pwd,
                        refNos}, this.queryParcelByRefNoServiceOperationCompleted, userState);
        }
        
        private void OnqueryParcelByRefNoServiceOperationCompleted(object arg) {
            if ((this.queryParcelByRefNoServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryParcelByRefNoServiceCompleted(this, new queryParcelByRefNoServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public returnObject[] forecastService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] vsnumbers) {
            object[] results = this.Invoke("forecastService", new object[] {
                        companyID,
                        pwd,
                        vsnumbers});
            return ((returnObject[])(results[0]));
        }
        
        /// <remarks/>
        public void forecastServiceAsync(string companyID, string pwd, string[] vsnumbers) {
            this.forecastServiceAsync(companyID, pwd, vsnumbers, null);
        }
        
        /// <remarks/>
        public void forecastServiceAsync(string companyID, string pwd, string[] vsnumbers, object userState) {
            if ((this.forecastServiceOperationCompleted == null)) {
                this.forecastServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnforecastServiceOperationCompleted);
            }
            this.InvokeAsync("forecastService", new object[] {
                        companyID,
                        pwd,
                        vsnumbers}, this.forecastServiceOperationCompleted, userState);
        }
        
        private void OnforecastServiceOperationCompleted(object arg) {
            if ((this.forecastServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.forecastServiceCompleted(this, new forecastServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public returnObject[] addParcelService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute("parcelList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] parcel[] parcelList) {
            object[] results = this.Invoke("addParcelService", new object[] {
                        companyID,
                        pwd,
                        parcelList});
            return ((returnObject[])(results[0]));
        }
        
        /// <remarks/>
        public void addParcelServiceAsync(string companyID, string pwd, parcel[] parcelList) {
            this.addParcelServiceAsync(companyID, pwd, parcelList, null);
        }
        
        /// <remarks/>
        public void addParcelServiceAsync(string companyID, string pwd, parcel[] parcelList, object userState) {
            if ((this.addParcelServiceOperationCompleted == null)) {
                this.addParcelServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddParcelServiceOperationCompleted);
            }
            this.InvokeAsync("addParcelService", new object[] {
                        companyID,
                        pwd,
                        parcelList}, this.addParcelServiceOperationCompleted, userState);
        }
        
        private void OnaddParcelServiceOperationCompleted(object arg) {
            if ((this.addParcelServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addParcelServiceCompleted(this, new addParcelServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public returnObject[] deleteParcelByNoService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("arrayOfString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] vsnumbers) {
            object[] results = this.Invoke("deleteParcelByNoService", new object[] {
                        companyID,
                        pwd,
                        vsnumbers});
            return ((returnObject[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteParcelByNoServiceAsync(string companyID, string pwd, string[] vsnumbers) {
            this.deleteParcelByNoServiceAsync(companyID, pwd, vsnumbers, null);
        }
        
        /// <remarks/>
        public void deleteParcelByNoServiceAsync(string companyID, string pwd, string[] vsnumbers, object userState) {
            if ((this.deleteParcelByNoServiceOperationCompleted == null)) {
                this.deleteParcelByNoServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteParcelByNoServiceOperationCompleted);
            }
            this.InvokeAsync("deleteParcelByNoService", new object[] {
                        companyID,
                        pwd,
                        vsnumbers}, this.deleteParcelByNoServiceOperationCompleted, userState);
        }
        
        private void OndeleteParcelByNoServiceOperationCompleted(object arg) {
            if ((this.deleteParcelByNoServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteParcelByNoServiceCompleted(this, new deleteParcelByNoServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://cxf.pl/", ResponseNamespace="http://cxf.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public returnObject[] addParcelAndForecastService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pwd, [System.Xml.Serialization.XmlElementAttribute("parcelList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] parcel[] parcelList) {
            object[] results = this.Invoke("addParcelAndForecastService", new object[] {
                        companyID,
                        pwd,
                        parcelList});
            return ((returnObject[])(results[0]));
        }
        
        /// <remarks/>
        public void addParcelAndForecastServiceAsync(string companyID, string pwd, parcel[] parcelList) {
            this.addParcelAndForecastServiceAsync(companyID, pwd, parcelList, null);
        }
        
        /// <remarks/>
        public void addParcelAndForecastServiceAsync(string companyID, string pwd, parcel[] parcelList, object userState) {
            if ((this.addParcelAndForecastServiceOperationCompleted == null)) {
                this.addParcelAndForecastServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddParcelAndForecastServiceOperationCompleted);
            }
            this.InvokeAsync("addParcelAndForecastService", new object[] {
                        companyID,
                        pwd,
                        parcelList}, this.addParcelAndForecastServiceOperationCompleted, userState);
        }
        
        private void OnaddParcelAndForecastServiceOperationCompleted(object arg) {
            if ((this.addParcelAndForecastServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addParcelAndForecastServiceCompleted(this, new addParcelAndForecastServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.pl/")]
    public partial class returnObject {
        
        private string vsnumberField;
        
        private string refNoField;
        
        private string trackingNoField;
        
        private string trackDedicatedNoField;
        
        private int errorCodeField;
        
        private bool successField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vsnumber {
            get {
                return this.vsnumberField;
            }
            set {
                this.vsnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string trackingNo {
            get {
                return this.trackingNoField;
            }
            set {
                this.trackingNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string trackDedicatedNo {
            get {
                return this.trackDedicatedNoField;
            }
            set {
                this.trackDedicatedNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.pl/")]
    public partial class shipTypeZoning {
        
        private string shipCodeField;
        
        private string countryCodeField;
        
        private string printZoneCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipCode {
            get {
                return this.shipCodeField;
            }
            set {
                this.shipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string printZoneCode {
            get {
                return this.printZoneCodeField;
            }
            set {
                this.printZoneCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.pl/")]
    public partial class parcel {
        
        private string vsnumberField;
        
        private System.DateTime apTdateField;
        
        private bool apTdateFieldSpecified;
        
        private int parcelstatusField;
        
        private string apmethodField;
        
        private string apnameField;
        
        private string apaddressField;
        
        private string address2Field;
        
        private string apdestinationField;
        
        private string aplabelField;
        
        private string aptrackingNumberField;
        
        private string apnoteField;
        
        private string apBuyerIDField;
        
        private string apItemurlField;
        
        private string apItemTitleField;
        
        private string apTransactionIDField;
        
        private string apFromEmailField;
        
        private string ebayIDField;
        
        private string apTelField;
        
        private string apTel2Field;
        
        private string zipCodeField;
        
        private string refNoField;
        
        private string apinsuranceField;
        
        private string aptypeField;
        
        private string apdescriptionField;
        
        private string customsArticleNameField;
        
        private int apquantityField;
        
        private bool apquantityFieldSpecified;
        
        private double apweightField;
        
        private double actualWeightField;
        
        private bool actualWeightFieldSpecified;
        
        private double apvalueField;
        
        private double apGrossField;
        
        private string apdescriptionsField;
        
        private string customsArticleNamesField;
        
        private string apquantitysField;
        
        private string apweightsField;
        
        private string apvaluesField;
        
        private string cityField;
        
        private string provinceField;
        
        private string skuField;
        
        private string imageUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vsnumber {
            get {
                return this.vsnumberField;
            }
            set {
                this.vsnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime apTdate {
            get {
                return this.apTdateField;
            }
            set {
                this.apTdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool apTdateSpecified {
            get {
                return this.apTdateFieldSpecified;
            }
            set {
                this.apTdateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int parcelstatus {
            get {
                return this.parcelstatusField;
            }
            set {
                this.parcelstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apmethod {
            get {
                return this.apmethodField;
            }
            set {
                this.apmethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apname {
            get {
                return this.apnameField;
            }
            set {
                this.apnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apaddress {
            get {
                return this.apaddressField;
            }
            set {
                this.apaddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apdestination {
            get {
                return this.apdestinationField;
            }
            set {
                this.apdestinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aplabel {
            get {
                return this.aplabelField;
            }
            set {
                this.aplabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aptrackingNumber {
            get {
                return this.aptrackingNumberField;
            }
            set {
                this.aptrackingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apnote {
            get {
                return this.apnoteField;
            }
            set {
                this.apnoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apBuyerID {
            get {
                return this.apBuyerIDField;
            }
            set {
                this.apBuyerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apItemurl {
            get {
                return this.apItemurlField;
            }
            set {
                this.apItemurlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apItemTitle {
            get {
                return this.apItemTitleField;
            }
            set {
                this.apItemTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apTransactionID {
            get {
                return this.apTransactionIDField;
            }
            set {
                this.apTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apFromEmail {
            get {
                return this.apFromEmailField;
            }
            set {
                this.apFromEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ebayID {
            get {
                return this.ebayIDField;
            }
            set {
                this.ebayIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apTel {
            get {
                return this.apTelField;
            }
            set {
                this.apTelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apTel2 {
            get {
                return this.apTel2Field;
            }
            set {
                this.apTel2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apinsurance {
            get {
                return this.apinsuranceField;
            }
            set {
                this.apinsuranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aptype {
            get {
                return this.aptypeField;
            }
            set {
                this.aptypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apdescription {
            get {
                return this.apdescriptionField;
            }
            set {
                this.apdescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customsArticleName {
            get {
                return this.customsArticleNameField;
            }
            set {
                this.customsArticleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int apquantity {
            get {
                return this.apquantityField;
            }
            set {
                this.apquantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool apquantitySpecified {
            get {
                return this.apquantityFieldSpecified;
            }
            set {
                this.apquantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double apweight {
            get {
                return this.apweightField;
            }
            set {
                this.apweightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double actualWeight {
            get {
                return this.actualWeightField;
            }
            set {
                this.actualWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actualWeightSpecified {
            get {
                return this.actualWeightFieldSpecified;
            }
            set {
                this.actualWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double apvalue {
            get {
                return this.apvalueField;
            }
            set {
                this.apvalueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double apGross {
            get {
                return this.apGrossField;
            }
            set {
                this.apGrossField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apdescriptions {
            get {
                return this.apdescriptionsField;
            }
            set {
                this.apdescriptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customsArticleNames {
            get {
                return this.customsArticleNamesField;
            }
            set {
                this.customsArticleNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apquantitys {
            get {
                return this.apquantitysField;
            }
            set {
                this.apquantitysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apweights {
            get {
                return this.apweightsField;
            }
            set {
                this.apweightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apvalues {
            get {
                return this.apvaluesField;
            }
            set {
                this.apvaluesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.pl/")]
    public partial class shipType {
        
        private string shipCodeField;
        
        private string shipNameField;
        
        private int traceableField;
        
        private string returnAddressField;
        
        private int barcodeAllocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipCode {
            get {
                return this.shipCodeField;
            }
            set {
                this.shipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipName {
            get {
                return this.shipNameField;
            }
            set {
                this.shipNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int traceable {
            get {
                return this.traceableField;
            }
            set {
                this.traceableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string returnAddress {
            get {
                return this.returnAddressField;
            }
            set {
                this.returnAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int barcodeAllocation {
            get {
                return this.barcodeAllocationField;
            }
            set {
                this.barcodeAllocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cxf.pl/")]
    public partial class parcelShippingCost {
        
        private string trackingNoField;
        
        private string refNoField;
        
        private double chargeField;
        
        private string currencyField;
        
        private double weightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string trackingNo {
            get {
                return this.trackingNoField;
            }
            set {
                this.trackingNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void forecastByRefNoServiceCompletedEventHandler(object sender, forecastByRefNoServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class forecastByRefNoServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal forecastByRefNoServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void queryParcelShippingCostByTarckingNoServiceCompletedEventHandler(object sender, queryParcelShippingCostByTarckingNoServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryParcelShippingCostByTarckingNoServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryParcelShippingCostByTarckingNoServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public parcelShippingCost[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((parcelShippingCost[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void deleteParcelByRefNoServiceCompletedEventHandler(object sender, deleteParcelByRefNoServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteParcelByRefNoServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteParcelByRefNoServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void queryParcelShippingCostByRefNoServiceCompletedEventHandler(object sender, queryParcelShippingCostByRefNoServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryParcelShippingCostByRefNoServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryParcelShippingCostByRefNoServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public parcelShippingCost[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((parcelShippingCost[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void changeShippingMethodByRefNoServiceCompletedEventHandler(object sender, changeShippingMethodByRefNoServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeShippingMethodByRefNoServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeShippingMethodByRefNoServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void queryShipTypeCompletedEventHandler(object sender, queryShipTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryShipTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryShipTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public shipType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((shipType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void queryParcelServiceCompletedEventHandler(object sender, queryParcelServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryParcelServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryParcelServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public parcel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((parcel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void queryShipTypeZoningCompletedEventHandler(object sender, queryShipTypeZoningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryShipTypeZoningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryShipTypeZoningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public shipTypeZoning[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((shipTypeZoning[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void changeShippingMethodServiceCompletedEventHandler(object sender, changeShippingMethodServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeShippingMethodServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeShippingMethodServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void queryParcelByRefNoServiceCompletedEventHandler(object sender, queryParcelByRefNoServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryParcelByRefNoServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryParcelByRefNoServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public parcel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((parcel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void forecastServiceCompletedEventHandler(object sender, forecastServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class forecastServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal forecastServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void addParcelServiceCompletedEventHandler(object sender, addParcelServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addParcelServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addParcelServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void deleteParcelByNoServiceCompletedEventHandler(object sender, deleteParcelByNoServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteParcelByNoServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteParcelByNoServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void addParcelAndForecastServiceCompletedEventHandler(object sender, addParcelAndForecastServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addParcelAndForecastServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addParcelAndForecastServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public returnObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((returnObject[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591